import { describe, it, expect } from 'vitest';
import { analyzeAIGenerated } from '../../../src/analyzers/ai-detection.js';
import type { FunctionInfo } from '../../../src/types.js';

function makeFn(name: string, start: number, bodyLines: number): FunctionInfo {
  return { name, startLine: start, endLine: start + bodyLines, parameterCount: 1, bodyLines, nestingDepth: 1, cyclomaticComplexity: 2 };
}

describe('AI detection analyzer', () => {
  it('detects AI-typical comment phrases', () => {
    const lines = [
      "// Here's the implementation for the module",
      'function foo() {',
      '  return 1;',
      '}',
      "// Let me explain how this works below",
      'function bar() {',
      '  return 2;',
      '}',
    ];
    const findings = analyzeAIGenerated(lines, []);
    expect(findings.some(f => f.message.includes('AI-typical phrases'))).toBe(true);
  });

  it('detects restating comments alongside other signals', () => {
    const lines = [
      '// initialize the user configuration object',
      'const userConfiguration = initUserConfiguration();',
      '// validate the input parameters',
      'validateInputParameters(params);',
      '// process the request data',
      'processRequestData(data);',
      "// Note that this is important",
      'doSomething();',
    ];
    const findings = analyzeAIGenerated(lines, []);
    expect(findings.some(f => f.message.includes('confidence'))).toBe(true);
  });

  it('detects explicit AI authorship markers with other signals', () => {
    const lines = [
      '// Generated by ChatGPT',
      "// Here's the implementation",
      'function hello() { return "hi"; }',
    ];
    const findings = analyzeAIGenerated(lines, []);
    expect(findings.some(f => f.message.includes('AI authorship marker'))).toBe(true);
  });

  it('detects step-by-step instruction comments', () => {
    const lines = [
      '// Step 1: Initialize the config',
      'const config = {};',
      '// Step 2: Load the data',
      'const data = load();',
      '// Step 3: Process everything',
      'process(data);',
    ];
    const findings = analyzeAIGenerated(lines, []);
    expect(findings.some(f => f.message.includes('Step-by-step'))).toBe(true);
  });

  it('returns no findings for clean human code', () => {
    const lines = [
      'const x = 1;',
      'const y = 2;',
      'function add(a, b) { return a + b; }',
    ];
    const findings = analyzeAIGenerated(lines, [makeFn('add', 3, 1)]);
    expect(findings).toHaveLength(0);
  });

  it('reports confidence percentage with multiple signals', () => {
    const lines = [
      "// Here's how to use this module",
      "// This function handles the main logic",
      'export function main() {',
      '  // Step 1: initialize',
      '  init();',
      '  // Step 2: run',
      '  run();',
      '  // Step 3: cleanup',
      '  cleanup();',
      '}',
    ];
    const findings = analyzeAIGenerated(lines, [makeFn('main', 3, 7)]);
    const main = findings.find(f => f.message.includes('confidence'));
    expect(main).toBeDefined();
    expect(main!.message).toMatch(/\d+%/);
  });

  it('gives higher confidence when many signals overlap', () => {
    const lines = [
      '// Generated with Claude',
      "// Here's the complete implementation",
      "// This function validates user input data",
      'export function validateUserInputData(data) {',
      '  // Step 1: Check if data exists',
      '  if (!data) return false;',
      '  // Step 2: Validate the format',
      '  if (!isValid(data)) return false;',
      '  // Step 3: Return the result',
      '  return true;',
      '}',
    ];
    const findings = analyzeAIGenerated(lines, [makeFn('validateUserInputData', 4, 7)]);
    const main = findings.find(f => f.message.includes('confidence'));
    expect(main).toBeDefined();
    const pct = parseInt(main!.message.match(/(\d+)%/)![1]);
    expect(pct).toBeGreaterThanOrEqual(40);
  });
});
